#
# GMT 6.5.0 Defaults file
#
# COLOR Parameters
#
COLOR_NAN                      = 180
#
# FONT Parameters
#
FONT_ANNOT_PRIMARY             = 10p,Helvetica,black
FONT_HEADING                   = 11p,Helvetica,black
#
# FORMAT Parameters
#
FORMAT_GEO_MAP                 = D
FORMAT_FLOAT_OUT               = %.6f
#
# MAP Parameters
#
MAP_ANNOT_OFFSET_PRIMARY       = 3p
MAP_ANNOT_OFFSET_SECONDARY     = 3p
MAP_DEFAULT_PEN                = thin,black
MAP_FRAME_PEN                  = thin,black
#
# Projection Parameters
#
PROJ_LENGTH_UNIT               = inch
#
# PostScript Parameters
#
PS_PAGE_ORIENTATION            = portrait
